// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
)

type Channel struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	Topic       sql.NullString `json:"topic"`
	Purpose     sql.NullString `json:"purpose"`
	IsPrivate   int64          `json:"is_private"`
	IsArchived  int64          `json:"is_archived"`
	IsShared    int64          `json:"is_shared"`
	IsGeneral   int64          `json:"is_general"`
	RawJson     string         `json:"raw_json"`
	UpdatedAt   string         `json:"updated_at"`
}

type EmbeddingJob struct {
	ID        int64  `json:"id"`
	ChannelID string `json:"channel_id"`
	Ts        string `json:"ts"`
	State     string `json:"state"`
	CreatedAt string `json:"created_at"`
}

type Message struct {
	ChannelID      string         `json:"channel_id"`
	Ts             string         `json:"ts"`
	WorkspaceID    string         `json:"workspace_id"`
	UserID         sql.NullString `json:"user_id"`
	Subtype        sql.NullString `json:"subtype"`
	ClientMsgID    sql.NullString `json:"client_msg_id"`
	ThreadTs       sql.NullString `json:"thread_ts"`
	ParentUserID   sql.NullString `json:"parent_user_id"`
	Text           string         `json:"text"`
	NormalizedText string         `json:"normalized_text"`
	ReplyCount     int64          `json:"reply_count"`
	LatestReply    sql.NullString `json:"latest_reply"`
	EditedTs       sql.NullString `json:"edited_ts"`
	DeletedTs      sql.NullString `json:"deleted_ts"`
	SourceRank     int64          `json:"source_rank"`
	SourceName     string         `json:"source_name"`
	RawJson        string         `json:"raw_json"`
	UpdatedAt      string         `json:"updated_at"`
}

type MessageEvent struct {
	ID          int64  `json:"id"`
	ChannelID   string `json:"channel_id"`
	Ts          string `json:"ts"`
	EventType   string `json:"event_type"`
	SourceName  string `json:"source_name"`
	PayloadJson string `json:"payload_json"`
	CreatedAt   string `json:"created_at"`
}

type MessageFile struct {
	WorkspaceID        string         `json:"workspace_id"`
	ChannelID          string         `json:"channel_id"`
	Ts                 string         `json:"ts"`
	FileID             string         `json:"file_id"`
	UserID             sql.NullString `json:"user_id"`
	Name               string         `json:"name"`
	Title              string         `json:"title"`
	Mimetype           sql.NullString `json:"mimetype"`
	Filetype           sql.NullString `json:"filetype"`
	PrettyType         sql.NullString `json:"pretty_type"`
	Mode               sql.NullString `json:"mode"`
	Size               int64          `json:"size"`
	UrlPrivate         sql.NullString `json:"url_private"`
	UrlPrivateDownload sql.NullString `json:"url_private_download"`
	Permalink          sql.NullString `json:"permalink"`
	IsPublic           int64          `json:"is_public"`
	PlainText          string         `json:"plain_text"`
	PreviewPlainText   string         `json:"preview_plain_text"`
	MediaPath          sql.NullString `json:"media_path"`
	ContentSha256      sql.NullString `json:"content_sha256"`
	ContentSize        int64          `json:"content_size"`
	FetchedAt          sql.NullString `json:"fetched_at"`
	FetchStatus        string         `json:"fetch_status"`
	FetchError         string         `json:"fetch_error"`
	RawJson            string         `json:"raw_json"`
	UpdatedAt          string         `json:"updated_at"`
}

type MessageFt struct {
	MessageKey string `json:"message_key"`
	Content    string `json:"content"`
}

type MessageMention struct {
	ChannelID   string         `json:"channel_id"`
	Ts          string         `json:"ts"`
	MentionType string         `json:"mention_type"`
	TargetID    string         `json:"target_id"`
	DisplayText sql.NullString `json:"display_text"`
}

type SyncState struct {
	SourceName string `json:"source_name"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Value      string `json:"value"`
	UpdatedAt  string `json:"updated_at"`
}

type User struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	RealName    sql.NullString `json:"real_name"`
	DisplayName sql.NullString `json:"display_name"`
	Title       sql.NullString `json:"title"`
	IsBot       int64          `json:"is_bot"`
	IsDeleted   int64          `json:"is_deleted"`
	RawJson     string         `json:"raw_json"`
	UpdatedAt   string         `json:"updated_at"`
}

type Workspace struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Domain       sql.NullString `json:"domain"`
	EnterpriseID sql.NullString `json:"enterprise_id"`
	RawJson      string         `json:"raw_json"`
	UpdatedAt    string         `json:"updated_at"`
}
