// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storedb

import (
	"context"
	"database/sql"
)

const channelSyncCursors = `-- name: ChannelSyncCursors :many
select c.id, cast(coalesce(max(case when m.ts not like 'draft:%' then m.ts end), '') as text) as latest_ts
from channels c
left join messages m on m.channel_id = c.id and m.workspace_id = c.workspace_id
where c.workspace_id = ?1
group by c.id
order by c.id asc
`

type ChannelSyncCursorsRow struct {
	ID       string `json:"id"`
	LatestTs string `json:"latest_ts"`
}

func (q *Queries) ChannelSyncCursors(ctx context.Context, workspaceID string) ([]ChannelSyncCursorsRow, error) {
	rows, err := q.db.QueryContext(ctx, channelSyncCursors, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelSyncCursorsRow
	for rows.Next() {
		var i ChannelSyncCursorsRow
		if err := rows.Scan(&i.ID, &i.LatestTs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChannels = `-- name: CountChannels :one
select count(*) from channels
`

func (q *Queries) CountChannels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChannels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
select count(*) from messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaces = `-- name: CountWorkspaces :one
select count(*) from workspaces
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessageFTS = `-- name: DeleteMessageFTS :exec
delete from message_fts where message_key = ?
`

func (q *Queries) DeleteMessageFTS(ctx context.Context, messageKey string) error {
	_, err := q.db.ExecContext(ctx, deleteMessageFTS, messageKey)
	return err
}

const deleteMessageFiles = `-- name: DeleteMessageFiles :exec
delete from message_files where channel_id = ? and ts = ?
`

type DeleteMessageFilesParams struct {
	ChannelID string `json:"channel_id"`
	Ts        string `json:"ts"`
}

func (q *Queries) DeleteMessageFiles(ctx context.Context, arg DeleteMessageFilesParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessageFiles, arg.ChannelID, arg.Ts)
	return err
}

const deleteMessageMentions = `-- name: DeleteMessageMentions :exec
delete from message_mentions where channel_id = ? and ts = ?
`

type DeleteMessageMentionsParams struct {
	ChannelID string `json:"channel_id"`
	Ts        string `json:"ts"`
}

func (q *Queries) DeleteMessageMentions(ctx context.Context, arg DeleteMessageMentionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessageMentions, arg.ChannelID, arg.Ts)
	return err
}

const getSyncState = `-- name: GetSyncState :one
select value from sync_state
where source_name = ? and entity_type = ? and entity_id = ?
`

type GetSyncStateParams struct {
	SourceName string `json:"source_name"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) GetSyncState(ctx context.Context, arg GetSyncStateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, arg.SourceName, arg.EntityType, arg.EntityID)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertMessageEvent = `-- name: InsertMessageEvent :exec
insert into message_events (channel_id, ts, event_type, source_name, payload_json, created_at)
values (?, ?, ?, ?, ?, ?)
`

type InsertMessageEventParams struct {
	ChannelID   string `json:"channel_id"`
	Ts          string `json:"ts"`
	EventType   string `json:"event_type"`
	SourceName  string `json:"source_name"`
	PayloadJson string `json:"payload_json"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertMessageEvent(ctx context.Context, arg InsertMessageEventParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageEvent,
		arg.ChannelID,
		arg.Ts,
		arg.EventType,
		arg.SourceName,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	return err
}

const insertMessageFTS = `-- name: InsertMessageFTS :exec
insert into message_fts (message_key, content) values (?, ?)
`

type InsertMessageFTSParams struct {
	MessageKey string `json:"message_key"`
	Content    string `json:"content"`
}

func (q *Queries) InsertMessageFTS(ctx context.Context, arg InsertMessageFTSParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageFTS, arg.MessageKey, arg.Content)
	return err
}

const insertMessageFile = `-- name: InsertMessageFile :exec
insert into message_files (
  workspace_id, channel_id, ts, file_id, user_id, name, title, mimetype, filetype,
  pretty_type, mode, size, url_private, url_private_download, permalink, is_public,
  plain_text, preview_plain_text, media_path, content_sha256, content_size, fetched_at,
  fetch_status, fetch_error, raw_json, updated_at
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(channel_id, ts, file_id) do update set
  workspace_id=excluded.workspace_id,
  user_id=excluded.user_id,
  name=excluded.name,
  title=excluded.title,
  mimetype=excluded.mimetype,
  filetype=excluded.filetype,
  pretty_type=excluded.pretty_type,
  mode=excluded.mode,
  size=excluded.size,
  url_private=excluded.url_private,
  url_private_download=excluded.url_private_download,
  permalink=excluded.permalink,
  is_public=excluded.is_public,
  plain_text=excluded.plain_text,
  preview_plain_text=excluded.preview_plain_text,
  media_path=excluded.media_path,
  content_sha256=excluded.content_sha256,
  content_size=excluded.content_size,
  fetched_at=excluded.fetched_at,
  fetch_status=excluded.fetch_status,
  fetch_error=excluded.fetch_error,
  raw_json=excluded.raw_json,
  updated_at=excluded.updated_at
`

type InsertMessageFileParams struct {
	WorkspaceID        string         `json:"workspace_id"`
	ChannelID          string         `json:"channel_id"`
	Ts                 string         `json:"ts"`
	FileID             string         `json:"file_id"`
	UserID             sql.NullString `json:"user_id"`
	Name               string         `json:"name"`
	Title              string         `json:"title"`
	Mimetype           sql.NullString `json:"mimetype"`
	Filetype           sql.NullString `json:"filetype"`
	PrettyType         sql.NullString `json:"pretty_type"`
	Mode               sql.NullString `json:"mode"`
	Size               int64          `json:"size"`
	UrlPrivate         sql.NullString `json:"url_private"`
	UrlPrivateDownload sql.NullString `json:"url_private_download"`
	Permalink          sql.NullString `json:"permalink"`
	IsPublic           int64          `json:"is_public"`
	PlainText          string         `json:"plain_text"`
	PreviewPlainText   string         `json:"preview_plain_text"`
	MediaPath          sql.NullString `json:"media_path"`
	ContentSha256      sql.NullString `json:"content_sha256"`
	ContentSize        int64          `json:"content_size"`
	FetchedAt          sql.NullString `json:"fetched_at"`
	FetchStatus        string         `json:"fetch_status"`
	FetchError         string         `json:"fetch_error"`
	RawJson            string         `json:"raw_json"`
	UpdatedAt          string         `json:"updated_at"`
}

func (q *Queries) InsertMessageFile(ctx context.Context, arg InsertMessageFileParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageFile,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.Ts,
		arg.FileID,
		arg.UserID,
		arg.Name,
		arg.Title,
		arg.Mimetype,
		arg.Filetype,
		arg.PrettyType,
		arg.Mode,
		arg.Size,
		arg.UrlPrivate,
		arg.UrlPrivateDownload,
		arg.Permalink,
		arg.IsPublic,
		arg.PlainText,
		arg.PreviewPlainText,
		arg.MediaPath,
		arg.ContentSha256,
		arg.ContentSize,
		arg.FetchedAt,
		arg.FetchStatus,
		arg.FetchError,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const lastSyncAt = `-- name: LastSyncAt :one
select cast(coalesce(max(updated_at), '') as text) as updated_at from sync_state where source_name != 'doctor'
`

func (q *Queries) LastSyncAt(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, lastSyncAt)
	var updated_at string
	err := row.Scan(&updated_at)
	return updated_at, err
}

const listChannelsByKind = `-- name: ListChannelsByKind :many
select workspace_id, id, name, kind
from channels
where (?1 = '' or workspace_id = ?1)
  and (?2 = '' or id = ?2 or name like ?3)
  and (?4 = '' or kind = ?4)
order by name asc
limit ?5
`

type ListChannelsByKindParams struct {
	WorkspaceID interface{} `json:"workspace_id"`
	Query       interface{} `json:"query"`
	QueryLike   string      `json:"query_like"`
	Kind        interface{} `json:"kind"`
	Limit       int64       `json:"limit"`
}

type ListChannelsByKindRow struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	Kind        string `json:"kind"`
}

func (q *Queries) ListChannelsByKind(ctx context.Context, arg ListChannelsByKindParams) ([]ListChannelsByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsByKind,
		arg.WorkspaceID,
		arg.Query,
		arg.QueryLike,
		arg.Kind,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsByKindRow
	for rows.Next() {
		var i ListChannelsByKindRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Name,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingFileMedia = `-- name: ListExistingFileMedia :many
select file_id, coalesce(media_path, '') as media_path,
       coalesce(content_sha256, '') as content_sha256, content_size,
       coalesce(fetched_at, '') as fetched_at, fetch_status, fetch_error
from message_files
where channel_id = ? and ts = ?
`

type ListExistingFileMediaParams struct {
	ChannelID string `json:"channel_id"`
	Ts        string `json:"ts"`
}

type ListExistingFileMediaRow struct {
	FileID        string `json:"file_id"`
	MediaPath     string `json:"media_path"`
	ContentSha256 string `json:"content_sha256"`
	ContentSize   int64  `json:"content_size"`
	FetchedAt     string `json:"fetched_at"`
	FetchStatus   string `json:"fetch_status"`
	FetchError    string `json:"fetch_error"`
}

func (q *Queries) ListExistingFileMedia(ctx context.Context, arg ListExistingFileMediaParams) ([]ListExistingFileMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listExistingFileMedia, arg.ChannelID, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExistingFileMediaRow
	for rows.Next() {
		var i ListExistingFileMediaRow
		if err := rows.Scan(
			&i.FileID,
			&i.MediaPath,
			&i.ContentSha256,
			&i.ContentSize,
			&i.FetchedAt,
			&i.FetchStatus,
			&i.FetchError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentions = `-- name: ListMentions :many
select m.workspace_id, mm.channel_id, mm.ts, mm.mention_type, mm.target_id, coalesce(mm.display_text, '') as display_text
from message_mentions mm
join messages m on m.channel_id = mm.channel_id and m.ts = mm.ts
where (?1 = '' or m.workspace_id = ?1)
  and (?2 = '' or mm.target_id = ?2 or mm.display_text like ?3)
order by mm.ts desc
limit ?4
`

type ListMentionsParams struct {
	WorkspaceID interface{}    `json:"workspace_id"`
	Target      interface{}    `json:"target"`
	TargetLike  sql.NullString `json:"target_like"`
	Limit       int64          `json:"limit"`
}

type ListMentionsRow struct {
	WorkspaceID string `json:"workspace_id"`
	ChannelID   string `json:"channel_id"`
	Ts          string `json:"ts"`
	MentionType string `json:"mention_type"`
	TargetID    string `json:"target_id"`
	DisplayText string `json:"display_text"`
}

func (q *Queries) ListMentions(ctx context.Context, arg ListMentionsParams) ([]ListMentionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMentions,
		arg.WorkspaceID,
		arg.Target,
		arg.TargetLike,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMentionsRow
	for rows.Next() {
		var i ListMentionsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.MentionType,
			&i.TargetID,
			&i.DisplayText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAll = `-- name: ListMessagesAll :many
select workspace_id, channel_id, ts, coalesce(user_id, '') as user_id, text, normalized_text, coalesce(thread_ts, '') as thread_ts, coalesce(subtype, '') as subtype
from messages
order by ts desc
limit ?1
`

type ListMessagesAllRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ChannelID      string `json:"channel_id"`
	Ts             string `json:"ts"`
	UserID         string `json:"user_id"`
	Text           string `json:"text"`
	NormalizedText string `json:"normalized_text"`
	ThreadTs       string `json:"thread_ts"`
	Subtype        string `json:"subtype"`
}

func (q *Queries) ListMessagesAll(ctx context.Context, limit int64) ([]ListMessagesAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesAllRow
	for rows.Next() {
		var i ListMessagesAllRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.UserID,
			&i.Text,
			&i.NormalizedText,
			&i.ThreadTs,
			&i.Subtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChannel = `-- name: ListMessagesByChannel :many
select workspace_id, channel_id, ts, coalesce(user_id, '') as user_id, text, normalized_text, coalesce(thread_ts, '') as thread_ts, coalesce(subtype, '') as subtype
from messages
where channel_id = ?1
order by ts desc
limit ?2
`

type ListMessagesByChannelParams struct {
	ChannelID string `json:"channel_id"`
	Limit     int64  `json:"limit"`
}

type ListMessagesByChannelRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ChannelID      string `json:"channel_id"`
	Ts             string `json:"ts"`
	UserID         string `json:"user_id"`
	Text           string `json:"text"`
	NormalizedText string `json:"normalized_text"`
	ThreadTs       string `json:"thread_ts"`
	Subtype        string `json:"subtype"`
}

func (q *Queries) ListMessagesByChannel(ctx context.Context, arg ListMessagesByChannelParams) ([]ListMessagesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByChannel, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByChannelRow
	for rows.Next() {
		var i ListMessagesByChannelRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.UserID,
			&i.Text,
			&i.NormalizedText,
			&i.ThreadTs,
			&i.Subtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChannelUser = `-- name: ListMessagesByChannelUser :many
select workspace_id, channel_id, ts, coalesce(user_id, '') as user_id, text, normalized_text, coalesce(thread_ts, '') as thread_ts, coalesce(subtype, '') as subtype
from messages
where channel_id = ?1
  and user_id = ?2
order by ts desc
limit ?3
`

type ListMessagesByChannelUserParams struct {
	ChannelID string         `json:"channel_id"`
	UserID    sql.NullString `json:"user_id"`
	Limit     int64          `json:"limit"`
}

type ListMessagesByChannelUserRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ChannelID      string `json:"channel_id"`
	Ts             string `json:"ts"`
	UserID         string `json:"user_id"`
	Text           string `json:"text"`
	NormalizedText string `json:"normalized_text"`
	ThreadTs       string `json:"thread_ts"`
	Subtype        string `json:"subtype"`
}

func (q *Queries) ListMessagesByChannelUser(ctx context.Context, arg ListMessagesByChannelUserParams) ([]ListMessagesByChannelUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByChannelUser, arg.ChannelID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByChannelUserRow
	for rows.Next() {
		var i ListMessagesByChannelUserRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.UserID,
			&i.Text,
			&i.NormalizedText,
			&i.ThreadTs,
			&i.Subtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByUser = `-- name: ListMessagesByUser :many
select workspace_id, channel_id, ts, coalesce(user_id, '') as user_id, text, normalized_text, coalesce(thread_ts, '') as thread_ts, coalesce(subtype, '') as subtype
from messages
where user_id = ?1
order by ts desc
limit ?2
`

type ListMessagesByUserParams struct {
	UserID sql.NullString `json:"user_id"`
	Limit  int64          `json:"limit"`
}

type ListMessagesByUserRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ChannelID      string `json:"channel_id"`
	Ts             string `json:"ts"`
	UserID         string `json:"user_id"`
	Text           string `json:"text"`
	NormalizedText string `json:"normalized_text"`
	ThreadTs       string `json:"thread_ts"`
	Subtype        string `json:"subtype"`
}

func (q *Queries) ListMessagesByUser(ctx context.Context, arg ListMessagesByUserParams) ([]ListMessagesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByUserRow
	for rows.Next() {
		var i ListMessagesByUserRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.UserID,
			&i.Text,
			&i.NormalizedText,
			&i.ThreadTs,
			&i.Subtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByWorkspace = `-- name: ListMessagesByWorkspace :many
select workspace_id, channel_id, ts, coalesce(user_id, '') as user_id, text, normalized_text, coalesce(thread_ts, '') as thread_ts, coalesce(subtype, '') as subtype
from messages
where workspace_id = ?1
order by ts desc
limit ?2
`

type ListMessagesByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int64  `json:"limit"`
}

type ListMessagesByWorkspaceRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ChannelID      string `json:"channel_id"`
	Ts             string `json:"ts"`
	UserID         string `json:"user_id"`
	Text           string `json:"text"`
	NormalizedText string `json:"normalized_text"`
	ThreadTs       string `json:"thread_ts"`
	Subtype        string `json:"subtype"`
}

func (q *Queries) ListMessagesByWorkspace(ctx context.Context, arg ListMessagesByWorkspaceParams) ([]ListMessagesByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByWorkspaceRow
	for rows.Next() {
		var i ListMessagesByWorkspaceRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.UserID,
			&i.Text,
			&i.NormalizedText,
			&i.ThreadTs,
			&i.Subtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByWorkspaceChannel = `-- name: ListMessagesByWorkspaceChannel :many
select workspace_id, channel_id, ts, coalesce(user_id, '') as user_id, text, normalized_text, coalesce(thread_ts, '') as thread_ts, coalesce(subtype, '') as subtype
from messages
where workspace_id = ?1
  and channel_id = ?2
order by ts desc
limit ?3
`

type ListMessagesByWorkspaceChannelParams struct {
	WorkspaceID string `json:"workspace_id"`
	ChannelID   string `json:"channel_id"`
	Limit       int64  `json:"limit"`
}

type ListMessagesByWorkspaceChannelRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ChannelID      string `json:"channel_id"`
	Ts             string `json:"ts"`
	UserID         string `json:"user_id"`
	Text           string `json:"text"`
	NormalizedText string `json:"normalized_text"`
	ThreadTs       string `json:"thread_ts"`
	Subtype        string `json:"subtype"`
}

func (q *Queries) ListMessagesByWorkspaceChannel(ctx context.Context, arg ListMessagesByWorkspaceChannelParams) ([]ListMessagesByWorkspaceChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByWorkspaceChannel, arg.WorkspaceID, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByWorkspaceChannelRow
	for rows.Next() {
		var i ListMessagesByWorkspaceChannelRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.UserID,
			&i.Text,
			&i.NormalizedText,
			&i.ThreadTs,
			&i.Subtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByWorkspaceChannelUser = `-- name: ListMessagesByWorkspaceChannelUser :many
select workspace_id, channel_id, ts, coalesce(user_id, '') as user_id, text, normalized_text, coalesce(thread_ts, '') as thread_ts, coalesce(subtype, '') as subtype
from messages
where workspace_id = ?1
  and channel_id = ?2
  and user_id = ?3
order by ts desc
limit ?4
`

type ListMessagesByWorkspaceChannelUserParams struct {
	WorkspaceID string         `json:"workspace_id"`
	ChannelID   string         `json:"channel_id"`
	UserID      sql.NullString `json:"user_id"`
	Limit       int64          `json:"limit"`
}

type ListMessagesByWorkspaceChannelUserRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ChannelID      string `json:"channel_id"`
	Ts             string `json:"ts"`
	UserID         string `json:"user_id"`
	Text           string `json:"text"`
	NormalizedText string `json:"normalized_text"`
	ThreadTs       string `json:"thread_ts"`
	Subtype        string `json:"subtype"`
}

func (q *Queries) ListMessagesByWorkspaceChannelUser(ctx context.Context, arg ListMessagesByWorkspaceChannelUserParams) ([]ListMessagesByWorkspaceChannelUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByWorkspaceChannelUser,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByWorkspaceChannelUserRow
	for rows.Next() {
		var i ListMessagesByWorkspaceChannelUserRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.UserID,
			&i.Text,
			&i.NormalizedText,
			&i.ThreadTs,
			&i.Subtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByWorkspaceUser = `-- name: ListMessagesByWorkspaceUser :many
select workspace_id, channel_id, ts, coalesce(user_id, '') as user_id, text, normalized_text, coalesce(thread_ts, '') as thread_ts, coalesce(subtype, '') as subtype
from messages
where workspace_id = ?1
  and user_id = ?2
order by ts desc
limit ?3
`

type ListMessagesByWorkspaceUserParams struct {
	WorkspaceID string         `json:"workspace_id"`
	UserID      sql.NullString `json:"user_id"`
	Limit       int64          `json:"limit"`
}

type ListMessagesByWorkspaceUserRow struct {
	WorkspaceID    string `json:"workspace_id"`
	ChannelID      string `json:"channel_id"`
	Ts             string `json:"ts"`
	UserID         string `json:"user_id"`
	Text           string `json:"text"`
	NormalizedText string `json:"normalized_text"`
	ThreadTs       string `json:"thread_ts"`
	Subtype        string `json:"subtype"`
}

func (q *Queries) ListMessagesByWorkspaceUser(ctx context.Context, arg ListMessagesByWorkspaceUserParams) ([]ListMessagesByWorkspaceUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByWorkspaceUser, arg.WorkspaceID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByWorkspaceUserRow
	for rows.Next() {
		var i ListMessagesByWorkspaceUserRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Ts,
			&i.UserID,
			&i.Text,
			&i.NormalizedText,
			&i.ThreadTs,
			&i.Subtype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncState = `-- name: ListSyncState :many
select source_name, entity_type, entity_id, value
from sync_state
where (?1 = '' or source_name = ?1)
  and (?2 = '' or entity_type = ?2)
order by updated_at desc, entity_id asc
limit ?3
`

type ListSyncStateParams struct {
	SourceName interface{} `json:"source_name"`
	EntityType interface{} `json:"entity_type"`
	Limit      int64       `json:"limit"`
}

type ListSyncStateRow struct {
	SourceName string `json:"source_name"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Value      string `json:"value"`
}

func (q *Queries) ListSyncState(ctx context.Context, arg ListSyncStateParams) ([]ListSyncStateRow, error) {
	rows, err := q.db.QueryContext(ctx, listSyncState, arg.SourceName, arg.EntityType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncStateRow
	for rows.Next() {
		var i ListSyncStateRow
		if err := rows.Scan(
			&i.SourceName,
			&i.EntityType,
			&i.EntityID,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select workspace_id, id, name, coalesce(real_name, '') as real_name, coalesce(display_name, '') as display_name, coalesce(title, '') as title
from users
where (?1 = '' or workspace_id = ?1)
  and (?2 = '' or id = ?2 or name like ?3 or real_name like ?3 or display_name like ?3)
order by name asc
limit ?4
`

type ListUsersParams struct {
	WorkspaceID interface{} `json:"workspace_id"`
	Query       interface{} `json:"query"`
	QueryLike   string      `json:"query_like"`
	Limit       int64       `json:"limit"`
}

type ListUsersRow struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	RealName    string `json:"real_name"`
	DisplayName string `json:"display_name"`
	Title       string `json:"title"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.WorkspaceID,
		arg.Query,
		arg.QueryLike,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Name,
			&i.RealName,
			&i.DisplayName,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameChannel = `-- name: RenameChannel :exec
update channels
set name = ?, updated_at = ?
where id = ?
`

type RenameChannelParams struct {
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RenameChannel(ctx context.Context, arg RenameChannelParams) error {
	_, err := q.db.ExecContext(ctx, renameChannel, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}

const setChannelArchived = `-- name: SetChannelArchived :exec
update channels
set is_archived = ?, updated_at = ?
where id = ?
`

type SetChannelArchivedParams struct {
	IsArchived int64  `json:"is_archived"`
	UpdatedAt  string `json:"updated_at"`
	ID         string `json:"id"`
}

func (q *Queries) SetChannelArchived(ctx context.Context, arg SetChannelArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setChannelArchived, arg.IsArchived, arg.UpdatedAt, arg.ID)
	return err
}

const setSyncState = `-- name: SetSyncState :exec
insert into sync_state (source_name, entity_type, entity_id, value, updated_at)
values (?, ?, ?, ?, ?)
on conflict(source_name, entity_type, entity_id) do update set
  value=excluded.value,
  updated_at=excluded.updated_at
`

type SetSyncStateParams struct {
	SourceName string `json:"source_name"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Value      string `json:"value"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) SetSyncState(ctx context.Context, arg SetSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, setSyncState,
		arg.SourceName,
		arg.EntityType,
		arg.EntityID,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const threadCoverageState = `-- name: ThreadCoverageState :one
select value from sync_state where source_name = 'doctor' and entity_type = 'threads' and entity_id = 'coverage'
`

func (q *Queries) ThreadCoverageState(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, threadCoverageState)
	var value string
	err := row.Scan(&value)
	return value, err
}

const updateFileFetchStatus = `-- name: UpdateFileFetchStatus :exec
update message_files
set fetched_at = ?,
    fetch_status = ?,
    fetch_error = ?,
    updated_at = ?
where channel_id = ? and ts = ? and file_id = ?
`

type UpdateFileFetchStatusParams struct {
	FetchedAt   sql.NullString `json:"fetched_at"`
	FetchStatus string         `json:"fetch_status"`
	FetchError  string         `json:"fetch_error"`
	UpdatedAt   string         `json:"updated_at"`
	ChannelID   string         `json:"channel_id"`
	Ts          string         `json:"ts"`
	FileID      string         `json:"file_id"`
}

func (q *Queries) UpdateFileFetchStatus(ctx context.Context, arg UpdateFileFetchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFileFetchStatus,
		arg.FetchedAt,
		arg.FetchStatus,
		arg.FetchError,
		arg.UpdatedAt,
		arg.ChannelID,
		arg.Ts,
		arg.FileID,
	)
	return err
}

const updateFileMedia = `-- name: UpdateFileMedia :exec
update message_files
set media_path = ?,
    content_sha256 = ?,
    content_size = ?,
    fetched_at = ?,
    fetch_status = ?,
    fetch_error = ?,
    updated_at = ?
where channel_id = ? and ts = ? and file_id = ?
`

type UpdateFileMediaParams struct {
	MediaPath     sql.NullString `json:"media_path"`
	ContentSha256 sql.NullString `json:"content_sha256"`
	ContentSize   int64          `json:"content_size"`
	FetchedAt     sql.NullString `json:"fetched_at"`
	FetchStatus   string         `json:"fetch_status"`
	FetchError    string         `json:"fetch_error"`
	UpdatedAt     string         `json:"updated_at"`
	ChannelID     string         `json:"channel_id"`
	Ts            string         `json:"ts"`
	FileID        string         `json:"file_id"`
}

func (q *Queries) UpdateFileMedia(ctx context.Context, arg UpdateFileMediaParams) error {
	_, err := q.db.ExecContext(ctx, updateFileMedia,
		arg.MediaPath,
		arg.ContentSha256,
		arg.ContentSize,
		arg.FetchedAt,
		arg.FetchStatus,
		arg.FetchError,
		arg.UpdatedAt,
		arg.ChannelID,
		arg.Ts,
		arg.FileID,
	)
	return err
}

const upsertChannel = `-- name: UpsertChannel :exec
insert into channels (id, workspace_id, name, kind, topic, purpose, is_private, is_archived, is_shared, is_general, raw_json, updated_at)
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(id) do update set
  workspace_id=excluded.workspace_id,
  name=excluded.name,
  kind=excluded.kind,
  topic=excluded.topic,
  purpose=excluded.purpose,
  is_private=excluded.is_private,
  is_archived=excluded.is_archived,
  is_shared=excluded.is_shared,
  is_general=excluded.is_general,
  raw_json=excluded.raw_json,
  updated_at=excluded.updated_at
`

type UpsertChannelParams struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	Topic       sql.NullString `json:"topic"`
	Purpose     sql.NullString `json:"purpose"`
	IsPrivate   int64          `json:"is_private"`
	IsArchived  int64          `json:"is_archived"`
	IsShared    int64          `json:"is_shared"`
	IsGeneral   int64          `json:"is_general"`
	RawJson     string         `json:"raw_json"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannel,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Kind,
		arg.Topic,
		arg.Purpose,
		arg.IsPrivate,
		arg.IsArchived,
		arg.IsShared,
		arg.IsGeneral,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertMessage = `-- name: UpsertMessage :exec
insert into messages (
  channel_id, ts, workspace_id, user_id, subtype, client_msg_id, thread_ts, parent_user_id,
  text, normalized_text, reply_count, latest_reply, edited_ts, deleted_ts, source_rank,
  source_name, raw_json, updated_at
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(channel_id, ts) do update set
  workspace_id=excluded.workspace_id,
  user_id=excluded.user_id,
  subtype=excluded.subtype,
  client_msg_id=excluded.client_msg_id,
  thread_ts=excluded.thread_ts,
  parent_user_id=excluded.parent_user_id,
  text=excluded.text,
  normalized_text=excluded.normalized_text,
  reply_count=excluded.reply_count,
  latest_reply=excluded.latest_reply,
  edited_ts=excluded.edited_ts,
  deleted_ts=excluded.deleted_ts,
  source_rank=case
    when excluded.source_rank <= messages.source_rank then excluded.source_rank
    else messages.source_rank
  end,
  source_name=case
    when excluded.source_rank <= messages.source_rank then excluded.source_name
    else messages.source_name
  end,
  raw_json=case
    when excluded.source_rank <= messages.source_rank then excluded.raw_json
    else messages.raw_json
  end,
  updated_at=excluded.updated_at
`

type UpsertMessageParams struct {
	ChannelID      string         `json:"channel_id"`
	Ts             string         `json:"ts"`
	WorkspaceID    string         `json:"workspace_id"`
	UserID         sql.NullString `json:"user_id"`
	Subtype        sql.NullString `json:"subtype"`
	ClientMsgID    sql.NullString `json:"client_msg_id"`
	ThreadTs       sql.NullString `json:"thread_ts"`
	ParentUserID   sql.NullString `json:"parent_user_id"`
	Text           string         `json:"text"`
	NormalizedText string         `json:"normalized_text"`
	ReplyCount     int64          `json:"reply_count"`
	LatestReply    sql.NullString `json:"latest_reply"`
	EditedTs       sql.NullString `json:"edited_ts"`
	DeletedTs      sql.NullString `json:"deleted_ts"`
	SourceRank     int64          `json:"source_rank"`
	SourceName     string         `json:"source_name"`
	RawJson        string         `json:"raw_json"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessage,
		arg.ChannelID,
		arg.Ts,
		arg.WorkspaceID,
		arg.UserID,
		arg.Subtype,
		arg.ClientMsgID,
		arg.ThreadTs,
		arg.ParentUserID,
		arg.Text,
		arg.NormalizedText,
		arg.ReplyCount,
		arg.LatestReply,
		arg.EditedTs,
		arg.DeletedTs,
		arg.SourceRank,
		arg.SourceName,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertMessageMention = `-- name: UpsertMessageMention :exec
insert into message_mentions (channel_id, ts, mention_type, target_id, display_text)
values (?, ?, ?, ?, ?)
on conflict(channel_id, ts, mention_type, target_id) do update set
  display_text=excluded.display_text
`

type UpsertMessageMentionParams struct {
	ChannelID   string         `json:"channel_id"`
	Ts          string         `json:"ts"`
	MentionType string         `json:"mention_type"`
	TargetID    string         `json:"target_id"`
	DisplayText sql.NullString `json:"display_text"`
}

func (q *Queries) UpsertMessageMention(ctx context.Context, arg UpsertMessageMentionParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessageMention,
		arg.ChannelID,
		arg.Ts,
		arg.MentionType,
		arg.TargetID,
		arg.DisplayText,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
insert into users (id, workspace_id, name, real_name, display_name, title, is_bot, is_deleted, raw_json, updated_at)
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(id) do update set
  workspace_id=excluded.workspace_id,
  name=excluded.name,
  real_name=excluded.real_name,
  display_name=excluded.display_name,
  title=excluded.title,
  is_bot=excluded.is_bot,
  is_deleted=excluded.is_deleted,
  raw_json=excluded.raw_json,
  updated_at=excluded.updated_at
`

type UpsertUserParams struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	RealName    sql.NullString `json:"real_name"`
	DisplayName sql.NullString `json:"display_name"`
	Title       sql.NullString `json:"title"`
	IsBot       int64          `json:"is_bot"`
	IsDeleted   int64          `json:"is_deleted"`
	RawJson     string         `json:"raw_json"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.RealName,
		arg.DisplayName,
		arg.Title,
		arg.IsBot,
		arg.IsDeleted,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
insert into workspaces (id, name, domain, enterprise_id, raw_json, updated_at)
values (?, ?, ?, ?, ?, ?)
on conflict(id) do update set
  name=excluded.name,
  domain=excluded.domain,
  enterprise_id=excluded.enterprise_id,
  raw_json=excluded.raw_json,
  updated_at=excluded.updated_at
`

type UpsertWorkspaceParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Domain       sql.NullString `json:"domain"`
	EnterpriseID sql.NullString `json:"enterprise_id"`
	RawJson      string         `json:"raw_json"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspace,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.EnterpriseID,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}
